# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_inputbs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 796)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico_file/sourcefile/bs.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QLabel{\n"
"    color: rgb(0, 0, 127);\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QComboBox{\n"
"    font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QLineEdit{\n"
"font: 12pt \"Microsoft Sans Serif\";\n"
"}\n"
"QTableView{\n"
"    border-color: rgb(0, 85, 0);\n"
"    \n"
"    alternate-background-color: rgb(230, 201, 255);\n"
"    background-color: rgb(199, 205, 255);\n"
"/*    selection-background-color: rgb(85, 255, 0);*/\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox{\n"
"font: 12pt \"Microsoft Sans Serif\";\n"
"    color: rgb(255, 85, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_scan = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_scan.sizePolicy().hasHeightForWidth())
        self.pushButton_scan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_scan.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico_file/sourcefile/Refresh.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_scan.setIcon(icon1)
        self.pushButton_scan.setObjectName("pushButton_scan")
        self.gridLayout.addWidget(self.pushButton_scan, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.pushButton_process = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_process.setEnabled(True)
        self.pushButton_process.setStyleSheet("font: 75 16pt \"Arial\";\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico_file/sourcefile/run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_process.setIcon(icon2)
        self.pushButton_process.setObjectName("pushButton_process")
        self.gridLayout.addWidget(self.pushButton_process, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 16pt \"Arial\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.textEdit_joblist = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(16)
        self.textEdit_joblist.setFont(font)
        self.textEdit_joblist.setStyleSheet("color: rgb(255, 0, 255);")
        self.textEdit_joblist.setObjectName("textEdit_joblist")
        self.horizontalLayout.addWidget(self.textEdit_joblist)
        self.textEdit_Log = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Ming Std")
        font.setPointSize(12)
        self.textEdit_Log.setFont(font)
        self.textEdit_Log.setStyleSheet("color: rgb(0, 0, 255);")
        self.textEdit_Log.setObjectName("textEdit_Log")
        self.horizontalLayout.addWidget(self.textEdit_Log)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView_data = QtWidgets.QTableView(self.centralwidget)
        self.tableView_data.setAlternatingRowColors(True)
        self.tableView_data.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_data.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_data.setObjectName("tableView_data")
        self.verticalLayout.addWidget(self.tableView_data)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 6)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1260, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.menu.setFont(font)
        self.menu.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menu.setToolTip("")
        self.menu.setWhatsThis("")
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_importxls = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico_file/sourcefile/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_importxls.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.action_importxls.setFont(font)
        self.action_importxls.setObjectName("action_importxls")
        self.action_output = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico_file/sourcefile/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_output.setIcon(icon4)
        self.action_output.setObjectName("action_output")
        self.action2 = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ico_file/sourcefile/8923926.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action2.setIcon(icon5)
        self.action2.setObjectName("action2")
        self.action_dele = QtWidgets.QAction(MainWindow)
        self.action_dele.setObjectName("action_dele")
        self.actionscan = QtWidgets.QAction(MainWindow)
        self.actionscan.setObjectName("actionscan")
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_scan, self.tableView_data)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Honour 鋪數錄入"))
        self.pushButton_scan.setText(_translate("MainWindow", "檢查補數資料"))
        self.label_2.setText(_translate("MainWindow", "一箱張數"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "排版個數"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.pushButton_process.setText(_translate("MainWindow", "處理"))
        self.label.setText(_translate("MainWindow", "狀態:"))
        self.textEdit_Log.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ff00ff;\">檢查報告!</span></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "配置"))
        self.action_importxls.setText(_translate("MainWindow", "匯入補數編號"))
        self.action_output.setText(_translate("MainWindow", "修改輸出PDF路徑"))
        self.action2.setText(_translate("MainWindow", "修改右邊和下邊出血位"))
        self.action2.setIconText(_translate("MainWindow", "修改右邊和下邊出血位"))
        self.action_dele.setText(_translate("MainWindow", "刪除行"))
        self.actionscan.setText(_translate("MainWindow", "掃描路徑"))
import resourcefile_rc
